### ISSUE TITLE
Linux Compile Error

### ISSUE THREAD

**Issue by A-Shahbazi** [nspire-emus/nspire_emu#1]
I try to compile nspire_emu using the instructions in README.md but it stops at following:

gcc -c -O3 -std=gnu11 -Wall -Wextra -flto -O3 -Wall -W -D_REENTRANT -fPIE -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I../../nspire_emu-qt -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I. -I. -o emu.o ../emu.c
../emu.c: In function ‘emulate’:
../emu.c:208:14: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(rom, 1, 0x80000, f);
              ^
../emu.c:265:14: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(boot2_ptr, 1, boot2_size, boot2_file);
              ^
../emu.c:197:11: internal compiler error: in update_ssa_across_abnormal_edges, at tree-inline.c:1853
     memset(rom, -1, 0x80000);
           ^

**Comment by Vogtinator** [comment]
That's a compiler bug, Legimet hit the same issue: https://www.omnimaga.org/ti-nspire-projects/ti-nspire-emulator/msg396927/#msg396927

**Comment by Legimet** [comment]
Yeah, I got the same ICE. It was using the version of GCC from Ubuntu 14.04.
