### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by antoniovazquezblanco** [nspire-emus/nspire_emu#2]
I want to make an Archlinux package of the emulator. I think it would be convenient to start tagging the code with the versions on the release in order to make packaging easier.

What do you think?

**Comment by Vogtinator** [comment]
Oh, definitely. Versioning would be quite important. I plan on fixing some bugs and then publishing a beta, what do you think? I wouldn't start doing tags right now as it changes more rapidly and chaotic right now.

**Comment by antoniovazquezblanco** [comment]
Seems perfect for me! I think it is quite ready for beta release :).

I was thinking in creating a folder in this repo with the basic script for ArchLinux package building.
I would also like to leave this open in order to get notified when you decide to tag the code.

**Comment by antoniovazquezblanco** [comment]
I see there's a tag! I will send a pull request with the packaging script for ArchLinux.

Thanks.

**Comment by antoniovazquezblanco** [comment]
Sorry to reopen the issue, but versioning convention may be conflictive.
Version strings cannot contain colons, hyphens or whitespaces in Archlinux. I don't know if v0.9-beta can be changed to something v0.9beta in future versions.

Thanks

**Comment by Vogtinator** [comment]
Then maybe use a tilde (~) instead?

**Comment by antoniovazquezblanco** [comment]
I don't think there's a problem with the '~' character in Archlinux but I don't really know about other Linux distros. Plus it is quite uncommon...

**Comment by adriweb** [comment]
He, debian things use it, for instance :
```
Conf grub-pc (2.02~beta2-22 Debian:testing [amd64])
Conf mysql-common (10.0.19+maria-1~wheezy MariaDB:mirror.stshosting.co.uk [all])
```

**Comment by antoniovazquezblanco** [comment]
```
$ makepkg -s
==> ERROR: pkgver is not allowed to contain colons, hyphens or whitespace.
```
I've used Ubuntu in the past, I now remember about tildes...
I personally prefer `v0.9beta` than using tilde but it is up to you :).

**Comment by Vogtinator** [comment]
It's not required that git tags are also the package version, so it doesn't really matter.

**Comment by antoniovazquezblanco** [comment]
I know but the thing is that if the tag matches the version I can avoid hardcoding a path so that packaging a new version is only changing the version number. Anyway it is not a problem, it only was a suggestion in order to make things easier for me.
I will adapt to the convention you choose.
Thanks!

**Comment by Vogtinator** [comment]
This is going to be the only tag with a suffix anyway, so it shouldn't be an issue.

**Comment by antoniovazquezblanco** [comment]
Perfect! Thanks ;)
