### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by Vogtinator** [nspire-emus/nspire_emu#4]
nspire_emu is already taken and nspire_emu-qt is not only boring and uninspired, it's even inconsistent in itself ('_' vs '-').
And ideas for a new name?
The least bad of mine was "Nexus", but that's already taken by google.

**Comment by antoniovazquezblanco** [comment]
Although I don't really like it I think that using the "nSpire" capitalization may be a good thing if possible (legal issues?). I will give it a thought although I'm not very good at this.

I would also like to suggest to change the default branch name from qt to master.

**Comment by adriweb** [comment]
I actually hate seeing the name mis-capitalized :P

But what about looking for some name on the side of the Phoenix ? 
Firebird ? FireBird ? Firebird Emu ?

That could also provide some source of inspiration for a logo redesign if needed, too.

**Comment by Vogtinator** [comment]
Same here, everybody writes "nspire" differently: "nspire", "nSpire", "Nspire", "NSpire".
All-lowercase is IMO the best option. I very much doubt that it would cause any legal trouble.

> I would also like to suggest to change the default branch name from qt to master.
That makes sense, now that the qt branch is working.

**Comment by antoniovazquezblanco** [comment]
A friend of mine suggested `emuspire`.
What do you think? What about capitalization?

**Comment by Ivoah** [comment]
I like the Firebird name

**Comment by Vogtinator** [comment]
emuspire sounds a bit "backwards"...
I like "Firebird Emu" as well

**Comment by adriweb** [comment]
Firebird Emu it is.

**Comment by adriweb** [comment]
I suppose the repo should be renamed as well ?

**Comment by Vogtinator** [comment]
Done. The github redirects should work fine, so we don't need to fix any links.
